"""
submit.py

Purpose
-------
This file validates the model's predictions and packages them into a
final submission file.

Responsibilities
• Read outputs/predictions.csv
• Read data/sample_submission.csv
• Validate that predictions are usable
• Save outputs/submission.csv
• Display the official evaluation report (reusing src/evaluation.py)

This file does NOT
• Train a model
• Preprocess data
• Load a saved model
• Modify prediction values
• Calculate metrics itself (that logic lives only in evaluation.py)
"""

import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent

# The evaluation module lives in src/, so it needs to be added to the
# import path. This keeps evaluation.py the single source of truth for
# metrics instead of copying its logic into submit.py.
sys.path.insert(0, str(REPO_ROOT / "src"))
from evaluation import load_metrics, display_final_report, generate_evaluation_reports  # noqa: E402

OUTPUTS_DIR = REPO_ROOT / "outputs"
PREDICTIONS_PATH = OUTPUTS_DIR / "predictions.csv"
SAMPLE_SUBMISSION_PATH = REPO_ROOT / "data" / "sample_submission.csv"
SUBMISSION_PATH = OUTPUTS_DIR / "submission.csv"
MODEL_PATH = OUTPUTS_DIR / "model.pkl"
HEALTH_REPORT_PATH = OUTPUTS_DIR / "health_report.txt"


def load_predictions():
    """Load the predictions generated by train.py."""
    if not PREDICTIONS_PATH.exists():
        print("Prediction file not found.")
        print("Please run 'python src/train.py' before generating a submission.")
        return None

    return pd.read_csv(PREDICTIONS_PATH)


def load_sample_submission():
    """Load the reference submission format."""
    if not SAMPLE_SUBMISSION_PATH.exists():
        print("Sample submission file not found.")
        print("Expected file at data/sample_submission.csv.")
        return None

    return pd.read_csv(SAMPLE_SUBMISSION_PATH)


def validate(predictions_df, sample_df):
    """Check that the predictions match the expected submission format."""
    # There should be exactly one column, and it should be named SalePrice.
    if list(predictions_df.columns) != ["SalePrice"]:
        print("Expected a SalePrice column.")
        return False

    # The number of predictions must match the number of test rows.
    if len(predictions_df) != len(sample_df):
        print("Prediction row count does not match test dataset.")
        return False

    return True


def build_submission(predictions_df, sample_df):
    """Combine the Id column with the predicted SalePrice values."""
    submission_df = pd.DataFrame({
        "Id": sample_df["Id"],
        "SalePrice": predictions_df["SalePrice"],
    })
    return submission_df


def main():
    """Validate predictions and create the final submission file."""
    try:
        predictions_df = load_predictions()
        if predictions_df is None:
            return

        sample_df = load_sample_submission()
        if sample_df is None:
            return

        if not validate(predictions_df, sample_df):
            return

        submission_df = build_submission(predictions_df, sample_df)

        SUBMISSION_PATH.parent.mkdir(parents=True, exist_ok=True)
        submission_df.to_csv(SUBMISSION_PATH, index=False)

        print("Submission file created successfully.")
        print(f"Saved to {SUBMISSION_PATH}")

        # Reuse the metrics that train.py already calculated on its
        # validation split. There is no ground-truth SalePrice for the
        # real test set, so submit.py cannot compute these itself.
        metrics = load_metrics()
        if metrics is None:
            print("Note: no training metrics found. Run 'python src/train.py' first for a full evaluation report.")
        else:
            display_final_report(
                metrics,
                submission_format_ok=True,
                prediction_count=len(submission_df),
                submission_saved=SUBMISSION_PATH.exists(),
            )

        # These are simple existence checks for the report, not metric
        # calculations - they just record which pipeline steps have run.
        generated_files = {
            "model.pkl": MODEL_PATH.exists(),
            "predictions.csv": PREDICTIONS_PATH.exists(),
            "submission.csv": SUBMISSION_PATH.exists(),
        }
        repository_status = {
            "Health Check": HEALTH_REPORT_PATH.exists(),
            "Training": metrics is not None,
            "Submission": SUBMISSION_PATH.exists(),
        }

        generate_evaluation_reports(
            metrics=metrics,
            submission_status="PASS",
            prediction_count=len(submission_df),
            submission_file=str(SUBMISSION_PATH.relative_to(REPO_ROOT)).replace("\\", "/"),
            generated_files=generated_files,
            repository_status=repository_status,
        )
        print("Evaluation reports generated successfully.")
    except Exception as exc:
        print("Something went wrong while creating the submission file.")
        print(f"Details: {exc}")


if __name__ == "__main__":
    main()
